definitions:
  github_com_yzimhao_trading_engine_v2_pkg_matching_types.OrderSide:
    enum:
    - bid
    - ask
    type: string
    x-enum-varnames:
    - OrderSideBuy
    - OrderSideSell
  github_com_yzimhao_trading_engine_v2_pkg_matching_types.OrderType:
    enum:
    - limit
    - market
    - marketQty
    - marketAmount
    type: string
    x-enum-varnames:
    - OrderTypeLimit
    - OrderTypeMarket
    - OrderTypeMarketQuantity
    - OrderTypeMarketAmount
  internal_modules_base_order.CreateOrderRequest:
    properties:
      amount:
        type: number
      order_type:
        allOf:
        - $ref: '#/definitions/github_com_yzimhao_trading_engine_v2_pkg_matching_types.OrderType'
        example: limit
      price:
        example: 1
        type: number
      qty:
        example: 12
        type: number
      side:
        allOf:
        - $ref: '#/definitions/github_com_yzimhao_trading_engine_v2_pkg_matching_types.OrderSide'
        example: buy
      symbol:
        example: btcusdt
        type: string
    required:
    - order_type
    - side
    - symbol
    type: object
info:
  contact: {}
paths:
  /api/v1/depth:
    get:
      consumes:
      - application/json
      description: get depth
      operationId: v1.depth
      parameters:
      - description: symbol
        in: query
        name: symbol
        required: true
        type: string
      - description: limit
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: depth
      tags:
      - market
  /api/v1/klines:
    get:
      consumes:
      - application/json
      description: 获取K线数据
      operationId: v1.klines
      parameters:
      - description: symbol
        in: query
        name: symbol
        required: true
        type: string
      - description: period
        enum:
        - M1
        - M3
        - M5
        - M15
        - M30
        - H1
        - H2
        - H4
        - H6
        - H8
        - H12
        - D1
        - D3
        - W1
        - MN
        in: query
        name: period
        type: string
      - description: start
        in: query
        name: start
        type: integer
      - description: end
        in: query
        name: end
        type: integer
      - description: limit
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: K线数据
      tags:
      - market
  /api/v1/order:
    post:
      consumes:
      - application/json
      operationId: v1.order
      parameters:
      - description: args
        in: body
        name: args
        required: true
        schema:
          $ref: '#/definitions/internal_modules_base_order.CreateOrderRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 创建订单
      tags:
      - order
  /api/v1/order/history:
    get:
      consumes:
      - application/json
      description: history list
      operationId: v1.user.order.history
      parameters:
      - description: symbol
        in: query
        name: symbol
        required: true
        type: string
      - description: start
        in: query
        name: start
        required: true
        type: integer
      - description: end
        in: query
        name: end
        required: true
        type: integer
      - description: limit
        in: query
        name: limit
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 历史订单
      tags:
      - 用户中心
  /api/v1/ping:
    get:
      description: test if the server is running
      operationId: v1.ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping
      tags:
      - base
  /api/v1/product:
    get:
      consumes:
      - application/json
      description: get product list
      operationId: v1.product.list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: product list
      tags:
      - product
  /api/v1/product/:symbol:
    get:
      consumes:
      - application/json
      description: 交易对详情
      operationId: v1.product
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 交易对详情
      tags:
      - product
  /api/v1/user/assets/query:
    post:
      consumes:
      - application/json
      description: 获取用户持仓资产接口
      operationId: v1.user.assets.query
      parameters:
      - description: symbols
        in: query
        name: symbols
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 用户持仓资产
      tags:
      - 用户中心
  /api/v1/user/order/trade/history:
    get:
      consumes:
      - application/json
      description: trade history list
      operationId: v1.order.trade_history
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 成交历史
      tags:
      - 用户中心
  /api/v1/user/order/unfinished:
    get:
      consumes:
      - application/json
      description: unfinished list
      operationId: v1.user.order.unfinished
      parameters:
      - description: symbol
        in: query
        name: symbol
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 未成交的订单
      tags:
      - 用户中心
  /api/v1/version:
    get:
      consumes:
      - application/json
      description: 程序版本号和编译相关信息
      operationId: v1.version
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: version
      tags:
      - base
swagger: "2.0"
