// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/asset/despoit": {
            "post": {
                "description": "despoit an asset",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "asset"
                ],
                "summary": "asset despoit",
                "operationId": "v1.asset.despoit",
                "parameters": [
                    {
                        "description": "despoit request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/app_api_handlers_controllers.DespoitRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/asset/transfer/{symbol}": {
            "post": {
                "description": "transfer an asset",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "asset"
                ],
                "summary": "asset transfer",
                "operationId": "v1.asset.transfer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "symbol",
                        "name": "symbol",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "transfer request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/app_api_handlers_controllers.TransferRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/asset/withdraw": {
            "post": {
                "description": "withdraw an asset",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "asset"
                ],
                "summary": "asset withdraw",
                "operationId": "v1.asset.withdraw",
                "parameters": [
                    {
                        "description": "withdraw request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/app_api_handlers_controllers.WithdrawRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/asset/{symbol}": {
            "get": {
                "description": "get an asset balance",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "asset"
                ],
                "summary": "get wallet asset",
                "operationId": "v1.asset.query",
                "parameters": [
                    {
                        "type": "string",
                        "description": "symbol",
                        "name": "symbol",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_yzimhao_trading_engine_v2_internal_persistence_gorm_entities.Asset"
                        }
                    }
                }
            }
        },
        "/api/v1/asset/{symbol}/history": {
            "get": {
                "description": "get an asset history",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "asset"
                ],
                "summary": "get asset history",
                "operationId": "v1.asset.history",
                "parameters": [
                    {
                        "type": "string",
                        "description": "symbol",
                        "name": "symbol",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_yzimhao_trading_engine_v2_internal_persistence_gorm_entities.Asset"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/base/exchange_info": {
            "get": {
                "description": "get exchange info",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "base"
                ],
                "summary": "exchange info",
                "operationId": "v1.base.exchange_info",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/market/depth": {
            "get": {
                "description": "get depth",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "market"
                ],
                "summary": "depth",
                "operationId": "v1.market.depth",
                "parameters": [
                    {
                        "type": "string",
                        "description": "symbol",
                        "name": "symbol",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "limit",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/market/klines": {
            "get": {
                "description": "获取K线数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "market"
                ],
                "summary": "klines",
                "operationId": "v1.market.klines",
                "parameters": [
                    {
                        "type": "string",
                        "description": "symbol",
                        "name": "symbol",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "limit",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/market/trades": {
            "get": {
                "description": "获取近期成交记录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "market"
                ],
                "summary": "trades",
                "operationId": "v1.market.trades",
                "parameters": [
                    {
                        "type": "string",
                        "description": "symbol",
                        "name": "symbol",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "limit",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/order/create": {
            "post": {
                "description": "create order",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "order"
                ],
                "summary": "create order",
                "operationId": "v1.order.create",
                "parameters": [
                    {
                        "description": "args",
                        "name": "args",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/app_api_handlers_controllers.OrderCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/order/history": {
            "get": {
                "description": "history list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "order"
                ],
                "summary": "history list",
                "operationId": "v1.order.history",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/order/trade/history": {
            "get": {
                "description": "trade history list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "order"
                ],
                "summary": "trade history list",
                "operationId": "v1.order.trade_history",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/order/unfinished": {
            "get": {
                "description": "unfinished list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "order"
                ],
                "summary": "unfinished list",
                "operationId": "v1.order.unfinished",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/ping": {
            "get": {
                "description": "test if the server is running",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "base"
                ],
                "summary": "ping",
                "operationId": "v1.ping",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "app_api_handlers_controllers.DespoitRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "app_api_handlers_controllers.OrderCreateRequest": {
            "type": "object",
            "required": [
                "order_type",
                "side",
                "symbol"
            ],
            "properties": {
                "amount": {
                    "type": "string",
                    "example": "100.00"
                },
                "order_type": {
                    "$ref": "#/definitions/github_com_yzimhao_trading_engine_v2_pkg_matching_types.OrderType"
                },
                "price": {
                    "type": "string",
                    "example": "1.00"
                },
                "qty": {
                    "type": "string",
                    "example": "12"
                },
                "side": {
                    "$ref": "#/definitions/github_com_yzimhao_trading_engine_v2_pkg_matching_types.OrderSide"
                },
                "symbol": {
                    "type": "string"
                }
            }
        },
        "app_api_handlers_controllers.TransferRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string"
                },
                "from": {
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                },
                "to": {
                    "type": "string"
                }
            }
        },
        "app_api_handlers_controllers.WithdrawRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "github_com_yzimhao_trading_engine_v2_internal_persistence_gorm_entities.Asset": {
            "type": "object",
            "properties": {
                "UUID": {
                    "type": "string"
                },
                "avail_balance": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "freeze_balance": {
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                },
                "total_balance": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "github_com_yzimhao_trading_engine_v2_pkg_matching_types.OrderSide": {
            "type": "string",
            "enum": [
                "BID",
                "ASK"
            ],
            "x-enum-varnames": [
                "OrderSideBuy",
                "OrderSideSell"
            ]
        },
        "github_com_yzimhao_trading_engine_v2_pkg_matching_types.OrderType": {
            "type": "string",
            "enum": [
                "limit",
                "market",
                "market_qty",
                "market_amount"
            ],
            "x-enum-varnames": [
                "OrderTypeLimit",
                "OrderTypeMarket",
                "OrderTypeMarketQuantity",
                "OrderTypeMarketAmount"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
