// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/wallet/assets/despoit": {
            "post": {
                "description": "despoit an asset",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wallet"
                ],
                "summary": "asset despoit",
                "operationId": "v1.wallet.asset.despoit",
                "parameters": [
                    {
                        "description": "despoit request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/app_api_handlers_controllers.DespoitRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/wallet/assets/withdraw": {
            "post": {
                "description": "withdraw an asset",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wallet"
                ],
                "summary": "asset withdraw",
                "operationId": "v1.wallet.asset.withdraw",
                "parameters": [
                    {
                        "description": "withdraw request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/app_api_handlers_controllers.WithdrawRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/wallet/assets/{symbol}": {
            "get": {
                "description": "get an asset balance",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wallet"
                ],
                "summary": "get wallet asset",
                "operationId": "v1.wallet.asset.query",
                "parameters": [
                    {
                        "type": "string",
                        "description": "symbol",
                        "name": "symbol",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_yzimhao_trading_engine_v2_internal_persistence_gorm_entities.Assets"
                        }
                    }
                }
            }
        },
        "/api/v1/wallet/assets/{symbol}/history": {
            "get": {
                "description": "get an asset history",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wallet"
                ],
                "summary": "get wallet asset history",
                "operationId": "v1.wallet.asset.history",
                "parameters": [
                    {
                        "type": "string",
                        "description": "symbol",
                        "name": "symbol",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_yzimhao_trading_engine_v2_internal_persistence_gorm_entities.Assets"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/wallet/transfer/{symbol}": {
            "post": {
                "description": "transfer an asset",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wallet"
                ],
                "summary": "asset transfer",
                "operationId": "v1.wallet.asset.transfer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "symbol",
                        "name": "symbol",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "transfer request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/app_api_handlers_controllers.TransferRequest"
                        }
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "app_api_handlers_controllers.DespoitRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "app_api_handlers_controllers.TransferRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string"
                },
                "from": {
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                },
                "to": {
                    "type": "string"
                }
            }
        },
        "app_api_handlers_controllers.WithdrawRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "github_com_yzimhao_trading_engine_v2_internal_persistence_gorm_entities.Assets": {
            "type": "object",
            "properties": {
                "UUID": {
                    "type": "string"
                },
                "avail_balance": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "freeze_balance": {
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                },
                "total_balance": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
